# Generated by Django 4.2.2 on 2023-08-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0004_alter_notification_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='text',
            new_name='context',
        ),
    ]
