# Generated by Django 4.2.2 on 2023-07-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='is_delted',
            new_name='is_deleted',
        ),
    ]
