# Generated by Django 4.2.2 on 2023-07-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story', '0002_rename_is_delted_story_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='story',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='Media_files'),
        ),
    ]
