# Generated by Django 4.2.2 on 2023-07-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_media_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='story',
        ),
    ]
