# Generated by Django 4.2.2 on 2023-06-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='Profile_img'),
        ),
    ]
