# Generated by Django 4.2.2 on 2023-06-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_customuser_is_veryfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_veryfied',
            new_name='is_verified',
        ),
    ]
