# Generated by Django 4.2.2 on 2023-06-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
