# Generated by Django 4.2.2 on 2023-07-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_delted',
            new_name='is_deleted',
        ),
    ]
