# Generated by Django 4.2.2 on 2023-07-18 17:36

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default=User.models.default_profile_image_path, upload_to='Profile_img'),
        ),
    ]
