# Generated by Django 4.2.2 on 2023-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_customuser_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='media/male.jpg', upload_to='Profile_img'),
        ),
    ]
