# Generated by Django 4.2.2 on 2023-07-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_comment_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
